version: 1.0.{build}
branches:
  only: 
  - master
clone_folder: C:\esnacc-ng
init:
- ps: >-
    mkdir C:\pthreads-win32

    $source = "ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip"

    $destination = "C:\pthreads-win32\pthreads-win32.zip"

    Invoke-WebRequest $source -OutFile $destination

    cd C:\pthreads-win32

    7z x C:\pthreads-win32\pthreads-win32.zip

    cd C:\esnacc-ng

build_script:
- '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\VsDevCmd"'
- C:\MinGW\msys\1.0\bin\bash -lc "echo \"C:/MinGW /mingw\" > /etc/fstab"
- C:\MinGW\msys\1.0\bin\bash -lc "cp /c/pthreads-win32/Pre-built.2/dll/x86/*.dll /c/esnacc-ng/."
- C:\MinGW\msys\1.0\bin\bash -lc "mv /bin/link.exe /bin/link_copy.exe"
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/esnacc-ng && ./boot.sh"
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/esnacc-ng && ./configure CC=build-aux/cccl CXX=build-aux/cccl LD=\"`which link`\" LIBS=\"-lws2_32 -liphlpapi\" --with-pthread=C:/pthreads-win32/Pre-built.2"
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/esnacc-ng && make "

- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/esnacc-ng && ./compiler/.libs/esnacc.exe -c -mo `dirname asn1specs/p-rec.c` asn1specs/p-rec.asn1"
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/esnacc-ng && ./compiler/.libs/esnacc.exe -C -mo `dirname cxx-examples/src/autotags.cpp` cxx-examples/src/autotags.asn1"
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/esnacc-ng && ./compiler/.libs/esnacc.exe -C -mo `dirname  cxx-examples/src/rfc1155-smi.cpp` cxx-examples/src/rfc1155-smi.asn1"
- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/esnacc-ng && ./compiler/.libs/esnacc.exe -C -mo `dirname  cxx-examples/src/rfc1157-snmp.cpp` cxx-examples/src/rfc1157-snmp.asn1 -I cxx-examples/src/"

- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/esnacc-ng && make c-examples/simple/genber.exe c-examples/simple/minbuf.exe c-examples/simple/expbuf.exe c-examples/simple/sbuf.exe c-examples/test-lib/testlib.exe cxx-examples/main.exe"

- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/esnacc-ng && ./c-examples/simple/.libs/genber.exe"

- C:\MinGW\msys\1.0\bin\bash -lc "cd /c/esnacc-ng && ./cxx-examples/.libs/main.exe"
